parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: ~
    database_name: servinow
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d293eea9b52181ff6ab43c32d2b731e0
    database_path: null
