servinow_entities:
    resource: "@ServinowEntitiesBundle/Resources/config/routing.yml"
    prefix:   /

servinow_movimientos_de_caja:
    resource: "@ServinowMovimientosDeCajaBundle/Resources/config/routing.yml"
    prefix:   /caja

servinow_navigation:
    resource: "@ServinowNavigationBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
