servinow_navigation:
    resource: "@ServinowNavigationBundle/Resources/config/routing.yml"
    prefix:   /

servinow_restaurant_drawer:
    resource: "@ServinowRestaurantDrawerBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
