parameters:
#    servinow_navigation.example.class: Servinow\NavigationBundle\Example

services:
#    servinow_navigation.example:
#        class: %servinow_navigation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
